src/posts/urls.py
from django.urls import path
from .views import create_posts_and_comments, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', create_posts_and_comments, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

src/proconnect/urls.py
from turtle import home
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import include, path
from  django.conf import settings
from  django.conf.urls.static import static
from django.views.static import serve 
import  debug_toolbar
from .views import home_view,register_request_user,login_request,logout_view,register_request_company,search_results

# app_name = 'proconnect'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view,name='home_view' ),
    path('__debug__/', include('debug_toolbar.urls')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('register_user/', register_request_user, name="register_user"),
    path('register_company/', register_request_company, name="register_company"),
    path('company_profile/',include('company_profile.urls',namespace='company_profile')),
    path('searchapp/',include('searchapp.urls',namespace='searchapp')),
     path("login", login_request, name="login"),
     path('search_results',search_results,name="search_results"),
     path("logout", logout_view, name="logout_view")
    ]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

src/profiles/urls.py
from django.urls import path
from .views import get_friends_list, my_profile_view,edit_skills,other_user,add_education,add_experience,add_skill,add_language,add_project,edit_language,edit_skill,edit_education,edit_project,edit_experience,delete_language,delete_skill,delete_education,delete_experience,delete_project,invites_received_view, profiles_list_view,invite_profiles_list_view, ProfileDetailView,ProfileListView,send_invitation,remove_from_friends,accept_invitation,reject_invitation,get_friends_list,map_view
app_name = 'profiles'

urlpatterns = [
 path('myprofile/', my_profile_view, name='my-profile-view'),
 path('add_education', add_education, name='add_education'),
 path('add_experience', add_experience, name='add_experience'),
 path('add_skill', add_skill, name='add_skill'),
path('add_language', add_language, name='add_language'),
path('add_project', add_project, name='add_project'),

path('edit_language/<int:id>/', edit_language, name='edit_language'),

path('edit_skill/<int:id>/', edit_skill, name='edit_skill'),
path('edit_project/<int:id>/', edit_project, name='edit_project'),
path('edit_education/<int:id>/', edit_education, name='edit_education'),
path('edit_experience/<int:id>/', edit_experience, name='edit_experience'),
path('edit_project/<int:id>/', edit_project, name='edit_project'),

path('delete_language/<int:id>/', delete_language, name='delete_language'),
path('delete_skill/<int:id>/', delete_skill, name='delete_skill'),
path('delete_education/<int:id>/', delete_education, name='delete_education'),
path('delete_experience/<int:id>/', delete_experience, name='delete_experience'),
path('delete_project/<int:id>/', delete_project, name='delete_project'),

 path('myprofile/edit/skills',edit_skills,name='edit-skills'), 
 path('map',map_view,name='map'),
  path('other_user/<int:id>/',other_user,name='other_user'),
  path('', ProfileListView.as_view(), name='all-profiles-view'),
  path('my-invites/', invites_received_view, name='my-invites-view'),
  path('friends_list/', get_friends_list, name='friends_list_view'),
  path('send-invite/', send_invitation, name='send-invite'),
  path('remove-friend/', remove_from_friends, name='remove-friend'),
  path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
  path('my-invites/accept/', accept_invitation, name='accept-invite'),
  path('my-invites/reject/', reject_invitation, name='reject-invite'),
 ]

src/profiles/forms.py
from attr import fields
from django import forms
from .models import Profile,Skills,Languages,Experience,Education , Projects
from django.forms.widgets import DateInput # need to import
class ProfileModilfy(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('first_name', 'last_name','about_us','headline','picture')

        
class SkillModilfy(forms.ModelForm):
    class Meta:
        model=Skills
        fields=('title', 'proficiency')


class LangModilfy(forms.ModelForm):
    class Meta:
        model=Languages
        fields=('language_name', 'proficiency')


class ExperienceModify(forms.ModelForm):
    class Meta:
        model=Experience
        fields=('title','employement_type','company_name','description','start_date','end_date','description','is_current')
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date':DateInput(attrs={'type': 'date'})
        }
class EducationModify(forms.ModelForm):
    class Meta:
        model=Education
        fields=('school','degree','field','start_date','end_date_expected','grade','description')
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date_expected':DateInput(attrs={'type': 'date'})
        }
class ProjectModify(forms.ModelForm):
    class Meta:
        model=Projects
        fields=('title','start_date','end_date','mentor','description','status')
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date':DateInput(attrs={'type': 'date'})
        }
        

src/profiles/views.py
from django import forms
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from requests import request
from .models import Profile , Skills  ,Address,Award,Education,Experience,Projects,Languages,Relationship
from .forms import ProfileModilfy ,SkillModilfy,LangModilfy,ExperienceModify,EducationModify,ProjectModify
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
import datetime
import folium
import geocoder
from django.db.models import Q
from .utils import get_ip_address,get_geo
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
def add_education(request):
    form=EducationModify()
    print('here')
    if request.method=='POST':
        print(request.POST)
        edu=Education.objects.create(profileID=request.user)
        form=EducationModify(request.POST,instance=edu)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)

def add_experience(request):
    form=ExperienceModify()
    if request.method=='POST':
        print(request.POST)
        exp=Experience.objects.create(profileID=request.user)
        form=ExperienceModify(request.POST,instance=exp)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)


def add_project(request):
    form=ProjectModify()
    if request.method=='POST':
        print(request.POST)
        exp=Projects.objects.create(profileID=request.user)
        form=ProjectModify(request.POST,instance=exp)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)
def add_language(request):
    form=LangModilfy()
    if request.method=='POST':
        print(request.POST)
        exp=Languages.objects.create(profileID=request.user)
        form=LangModilfy(request.POST,instance=exp)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)

def add_skill(request):
    form=SkillModilfy()
    if request.method=='POST':
        print(request.POST)
        exp=Skills.objects.create(profileID=request.user)
        form=SkillModilfy(request.POST,instance=exp)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)
def edit_language(request,id):
    lang=Languages.objects.get(id=id)
    form=LangModilfy(instance=lang)
    if request.method=='POST':
        print(request.POST)
        
        if(lang.profileID!=request.user):
            return HttpResponseNotFound('<h1>Invalid access </h1>')
        form=LangModilfy(request.POST,instance=lang)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)

def edit_skill(request,id):
    lang=Skills.objects.get(id=id)
    form=SkillModilfy(instance=lang)
    if request.method=='POST':
        print(request.POST)
        
        if(lang.profileID!=request.user):
            return HttpResponseNotFound('<h1>Invalid access </h1>')
        form=SkillModilfy(request.POST,instance=lang)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)

def edit_education(request,id):
    lang=Education.objects.get(id=id)
    form=EducationModify(instance=lang)
    if request.method=='POST':
        print(request.POST)
        
        if(lang.profileID!=request.user):
            return HttpResponseNotFound('<h1>Invalid access </h1>')
        form=EducationModify(request.POST,instance=lang)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)

def edit_project(request,id):
    lang=Projects.objects.get(id=id)
    form=ProjectModify(instance=lang)
    if request.method=='POST':
        print(request.POST)
      
        if(lang.profileID!=request.user):
            return HttpResponseNotFound('<h1>Invalid access </h1>')
        form=ProjectModify(request.POST,instance=lang)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)
def edit_experience(request,id):
    lang=Experience.objects.get(id=id)
    form=ExperienceModify(instance=lang)
    if request.method=='POST':
        print(request.POST)
        
        if(lang.profileID!=request.user):
            return HttpResponseNotFound('<h1>Invalid access </h1>')
        form=ExperienceModify(request.POST,instance=lang)
        if form.is_valid():
            form.save()
        return redirect('/profiles/myprofile/')
    dic={'form':form}
    return render(request,'profiles/form.html',dic)

def delete_skill(request,id):
    Skills.objects.get(id=id).delete()
    return redirect('/profiles/myprofile/')
def delete_language(request,id):
    Languages.objects.get(id=id).delete()
    return redirect('/profiles/myprofile/')
def delete_education(request,id):
    Education.objects.get(id=id).delete()
    return redirect('/profiles/myprofile/')
def delete_experience(request,id):
    Experience.objects.get(id=id).delete()
    return redirect('/profiles/myprofile/')
def delete_project(request,id):
    Projects.objects.get(id=id).delete()
    return redirect('/profiles/myprofile/')

    
    
def other_user(request,id):
    print('no found',id)
    user=get_object_or_404(User,id=id)
    print('user_found')
    print(user)
    profile = get_object_or_404(Profile,user=user)
    print('profiler_found')
    rel_r = Relationship.objects.filter(sender=profile)
    rel_s = Relationship.objects.filter(receiver=profile)
    rel_receiver = []
    rel_sender = []
    for item in rel_r:
        rel_receiver.append(item.receiver.user)
    for item in rel_s:
        rel_sender.append(item.sender.user)
    print(rel_sender)
    print(rel_receiver)
    try:
        educations=list(Education.objects.filter(profileID=user).order_by('start_date'))
    except Education.DoesNotExist:
        educations=None
    try:
        awards=list(Award.objects.filter(profileID=user))
    except Award.DoesNotExist:
        awards=None
    try:
        experiences=list(Experience.objects.filter(profileID=user).order_by('start_date'))
    except Experience.DoesNotExist:
        experiences=None
    try:
        projects=list(Projects.objects.filter(profileID=user).order_by('start_date'))
    except Experience.DoesNotExist:
        projects=None
    try:
        skills=list(Skills.objects.filter(profileID=user).order_by('proficiency'))
    except Experience.DoesNotExist:
        skills=None
    try:
        languages=list(Languages.objects.filter(profileID=user))
    except Experience.DoesNotExist:
        languages=None
    
    dic={
        'user':user,
        'profile':profile,
        'skills':skills,
        'educations':educations,
        'awards':awards,
        'experiences':experiences,
        'projects':projects,
        'languages':languages,
        'rel_receiver': rel_receiver,
        'rel_sender': rel_sender
    }

    return render(request,'profiles/other_user.html',dic)

def map_view(request):
    
    
    # Create Map Object
    map = folium.Map(location=[19, -12], zoom_start=2)
    ip=get_ip_address(request)
    country, city, lat, lon=get_geo(ip)
    folium.Marker([lat, lon], tooltip='Click for more',
                  popup=country).add_to(map)
    # Get HTML Representation of Map Object
    map = map._repr_html_()
    context = {
        'map': map,
    }
    return render(request, 'profiles/map.html', context)

def check_if_starts(dic,word):
    
    return  {key:val for key, val in dic.items() 
                   if key.startswith(word)}

def edit_skills(request):
    try:
        skills=list(Skills.objects.all().filter(profileID=request.user))
    except Skills.DoesNotExist:
         skills=None
    
    if skills==None:
        return HttpResponseRedirect("profiles/myprofile")
    forms_skill=[]
    for i in skills:
        print(len(forms_skill))
        print((i.title))
        print("------------------printing form----------")
        fo=SkillModilfy(request.POST,instance=i)
        print(fo)
        forms_skill.append(fo)
        print("in for loop",forms_skill)
    # for x in forms_skill:
    #     print("------------------printing form----------")
    #     print(x)

    # if request.method == 'POST':
        
    #     skill=Skills.objects.filter(id=request.POST.get('id'))[0]
    #     idx=0
    #     while skill != skills[idx]:
    #         idx+=1
    #     print(skill)
    #     print(vars(skill))
    #     post=request.POST
        
    #     skill.title=post.getlist('title')[idx]
    #     skill.proficiency=int(post.getlist('proficiency')[idx])
    #     skill.save()
        

        
        
    
    dic={ 
            'skills':skills,
                'forms_skill':forms_skill,
                'skill_zip':zip(forms_skill,skills)
            }
    return  render(request,'profiles/skill_edit_form.html',dic)
    

def my_profile_view(request):
    # print("Userid->",request.user)
    profile = get_object_or_404(Profile,user=request.user)
    try:
        address=list(Address.objects.filter(profileID=request.user))
    except Address.DoesNotExist:
        address=None
    try:
        skills=list(Skills.objects.filter(profileID=request.user))
    except Skills.DoesNotExist:

src/profiles/templates/profiles/form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<form action='' method="post">

    {% csrf_token %}

       {{form|crispy}}
       <button type="submit" class="btn btn-block btn-primary btn-md" id="register_user_submit" name="add_education" data-mdb-ripple-color="dark">Submit</button>
   </form>
  
{% endblock content %}

src/profiles/templates/profiles/friends_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}


{% for obj in qs %}
{% if request.user in obj.friends.all %}
<div class="ui segment">
    <div class="ui grid">
        <div class="row">
            <div class="three wide column">
                <img class="ui small circular image" src={{obj.picture.url}}>
            </div>
            <div class="thirteen wide column">
                <h3>{{obj.user}}</h3>
                <p>{{obj.bio}}</p>
                <a href="{% url 'profiles:other_user'  obj.user.id %}"><button class="ui primary button mb-5 w-big">See
                        profile</button></a>
                <br>              
            </div>

        </div>
    </div>
</div>
{% endif %}
{% endfor %}
{% endblock content %}

src/profiles/templates/profiles/map.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}

<body class="text-left">
   <div class="container">
       <div class="row mt-4">
           <div class="col-md-10 offset-md-1">
               {{ map|safe }}
           </div>
       </div>
   </div>
            
          

</body>


<style type="text/css">
    
    body {
        color: #6c757d;
        background-color: #f5f6f8;
        margin-top: 20px;
    }
    

    .card-box {
        background-color: #fff;
        background-clip: border-box;
        border: 1px solid #e7eaed;
        padding: 1.5rem;
        margin-bottom: 24px;
        border-radius: .25rem;
    }

    .avatar-xl {
        height: 6rem;
        width: 6rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .nav-pills .nav-link.active,
    .nav-pills .show>.nav-link {
        color: #fff;
        background-color: #1abc9c;
    }

    .nav-pills .nav-link {
        border-radius: .25rem;
    }

    .navtab-bg li>a {
        background-color: #f7f7f7;
        margin: 0 5px;
    }

    .nav-pills>li>a,
    .nav-tabs>li>a {
        color: #6c757d;
        font-weight: 600;
    }

    .mb-4,
    .my-4 {
        margin-bottom: 2.25rem !important;
    }

    .tab-content {
        padding: 20px 0 0 0;
    }

    .progress-sm {
        height: 5px;
    }
    .progress-lg {
        height: 30px;
    }
    .m-0 {
        margin: 0 !important;
    }

    .table .thead-light th {
        color: #6c757d;
        background-color: #f1f5f7;
        border-color: #dee2e6;
    }

    .social-list-item {
        height: 2rem;
        width: 2rem;
        line-height: calc(2rem - 4px);
        display: block;
        border: 2px solid #adb5bd;
        border-radius: 50%;
        color: #adb5bd;
    }

    .text-purple {
        color: #6559cc !important;
    }

    .border-purple {
        border-color: #6559cc !important;
    }

    .timeline {
        margin-bottom: 50px;
        position: relative;
    }

    .timeline:before {
        background-color: #dee2e6;
        bottom: 0;
        content: "";
        left: 50%;
        position: absolute;
        top: 30px;
        width: 2px;
        z-index: 0;
    }

    .timeline .time-show {
        margin-bottom: 30px;
        margin-top: 30px;
        position: relative;
    }

    .timeline .timeline-box {
        background: #fff;
        display: block;
        margin: 15px 0;
        position: relative;
        padding: 20px;
    }

    .timeline .timeline-album {
        margin-top: 12px;
    }

    .timeline .timeline-album a {
        display: inline-block;
        margin-right: 5px;
    }

    .timeline .timeline-album img {
        height: 36px;
        width: auto;
        border-radius: 3px;
    }

    @media (min-width: 768px) {
        .timeline .time-show {
            margin-right: -69px;
            text-align: right;
        }

        .timeline .timeline-box {
            margin-left: 45px;
        }

        .timeline .timeline-icon {
            background: #dee2e6;
            border-radius: 50%;
            display: block;
            height: 20px;
            left: -54px;
            margin-top: -10px;
            position: absolute;
            text-align: center;
            top: 50%;
            width: 20px;
        }

        .timeline .timeline-icon i {
            color: #98a6ad;
            font-size: 13px;
            position: absolute;
            left: 4px;
        }

        .timeline .timeline-desk {
            display: table-cell;
            vertical-align: top;
            width: 50%;
        }

        .timeline-item {
            display: table-row;
        }

        .timeline-item:before {
            content: "";
            display: block;
            width: 50%;
        }

        .timeline-item .timeline-desk .arrow {
            border-bottom: 12px solid transparent;
            border-right: 12px solid #fff !important;
            border-top: 12px solid transparent;
            display: block;
            height: 0;
            left: -12px;
            margin-top: -12px;
            position: absolute;
            top: 50%;
            width: 0;
        }

        .timeline-item.timeline-item-left:after {
            content: "";
            display: block;
            width: 50%;
        }

        .timeline-item.timeline-item-left .timeline-desk .arrow-alt {
            border-bottom: 12px solid transparent;
            border-left: 12px solid #fff !important;
            border-top: 12px solid transparent;
            display: block;
            height: 0;
            left: auto;
            margin-top: -12px;
            position: absolute;
            right: -12px;
            top: 50%;
            width: 0;
        }

        .timeline-item.timeline-item-left .timeline-desk .album {
            float: right;
            margin-top: 20px;
        }

        .timeline-item.timeline-item-left .timeline-desk .album a {
            float: right;
            margin-left: 5px;
        }

        .timeline-item.timeline-item-left .timeline-icon {
            left: auto;
            right: -56px;
        }

        .timeline-item.timeline-item-left:before {
            display: none;
        }

        .timeline-item.timeline-item-left .timeline-box {
            margin-right: 45px;
            margin-left: 0;
            text-align: right;
        }
    }

    @media (max-width: 767.98px) {
        .timeline .time-show {
            text-align: center;
            position: relative;
        }

        .timeline .timeline-icon {
            display: none;
        }
    }

    .timeline-sm {
        padding-left: 110px;
    }

    .timeline-sm .timeline-sm-item {
        position: relative;
        padding-bottom: 20px;
        padding-left: 40px;
        border-left: 2px solid #dee2e6;
    }

    .timeline-sm .timeline-sm-item:after {
        content: "";
        display: block;
        position: absolute;
        top: 3px;
        left: -7px;
        width: 12px;
        height: 12px;
        border-radius: 50%;
        background: #fff;
        border: 2px solid #1abc9c;
    }

    .timeline-sm .timeline-sm-item .timeline-sm-date {
        position: absolute;
        left: -104px;
    }

    @media (max-width: 420px) {
        .timeline-sm {
            padding-left: 0;
        }

        .timeline-sm .timeline-sm-date {
            position: relative !important;
            display: block;
            left: 0 !important;
            margin-bottom: 10px;
        }
    }
</style>

<script type="text/javascript">

</script>
{% endblock content %}

src/profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}

{% if is_empty %}
<h1>No invitations here..</h1>
{% endif %}

{% for obj in qs %}
<div class="ui segment">
    <div class="ui grid">
        <div class="row">
            <div class="three wide column">
                <img class="ui small circular image" src={{obj.avatar.url}}>
            </div>
            <div class="thirteen wide column">
                <h3>{{obj.user}}</h3>
                <p>{{obj.bio}}</h3>
                    <br>
                    <a href="">
                        <button class="ui primary button w-big mb-5">See profile</button>
                    </a>
                <form action="{% url 'profiles:accept-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    <button type="submit" class="ui positive basic button w-big mb-5">
                        <i class="check icon"></i>
                        Accept invite
                    </button>
                </form>
                <form action="{% url 'profiles:reject-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    <button type="submit" class="ui negative basic button w-big mb-5">
                        <i class="close icon"></i>
                        Reject invite
                    </button>
                </form>
            </div>

        </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

src/profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}

{% if is_empty %}
<h1>No profiles to interact with</h1>
{% endif %}

{% for obj in object_list %}
<div class="ui segment">
    <div class="ui grid">
        <div class="row">
            <div class="three wide column">
                <img class="ui small circular image" src={{obj.picture.url}}>
            </div>
            <div class="thirteen wide column">
                <h3>{{obj.user}}</h3>
                <p>{{obj.bio}}</p>
                <a href= "{% url 'profiles:other_user'  obj.user.id %}"><button class="ui primary button mb-5 w-big">See profile</button></a>
                <br>

                {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                <form action="{% url 'profiles:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i
                            class="plus square icon"></i>Add to friends</button>
                </form>
                {% endif %}

                {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                {% endif %}

                {% if request.user in obj.friends.all %}
                <form action="{% url 'profiles:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i
                            class="minus square icon"></i>Remove from friends</button>
                </form>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}