src/company_profile/urls.py
from django.urls import path
from .views import my_profile_company_view , single_job_view, job_list,saved_job_list,edit_job_view,view_applications,applied_job_list,other_company

app_name = 'company_profile'

urlpatterns = [
path('myprofile', my_profile_company_view, name='my_profile_company_view'),
path('single_job/<int:id>/', single_job_view, name="single_job_view"),
path('job_list/', job_list, name='job_list'),
path('saved_job_list/',saved_job_list,name='saved_job_list'),
path('applied_job_list/',applied_job_list,name='applied_job_list'),
path('other_company/<int:id>/',other_company,name='other_company'),

path('edit_job_view/<int:id>/',edit_job_view,name='edit_job_view'),
path('view_applications/<int:id>/',view_applications,name='view_applications'),

 ]

src/posts/urls.py
from django.urls import path
from .views import create_posts_and_comments, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', create_posts_and_comments, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

src/proconnect/urls.py
from turtle import home
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import include, path
from  django.conf import settings
from  django.conf.urls.static import static
from django.views.static import serve 
import  debug_toolbar
from .views import home_view,register_request_user,login_request,logout_view,register_request_company,search_results

# app_name = 'proconnect'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view,name='home_view' ),
    path('__debug__/', include('debug_toolbar.urls')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('register_user/', register_request_user, name="register_user"),
    path('register_company/', register_request_company, name="register_company"),
    path('company_profile/',include('company_profile.urls',namespace='company_profile')),
    path('searchapp/',include('searchapp.urls',namespace='searchapp')),
     path("login", login_request, name="login"),
     path('search_results',search_results,name="search_results"),
     path("logout", logout_view, name="logout_view")
    ]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

src/profiles/urls.py
from django.urls import path
from .views import get_friends_list, my_profile_view,edit_skills,other_user,add_education,add_experience,add_skill,add_language,add_project,edit_language,edit_skill,edit_education,edit_project,edit_experience,delete_language,delete_skill,delete_education,delete_experience,delete_project,invites_received_view, profiles_list_view,invite_profiles_list_view, ProfileDetailView,ProfileListView,send_invitation,remove_from_friends,accept_invitation,reject_invitation,get_friends_list,map_view
app_name = 'profiles'

urlpatterns = [
 path('myprofile/', my_profile_view, name='my-profile-view'),
 path('add_education', add_education, name='add_education'),
 path('add_experience', add_experience, name='add_experience'),
 path('add_skill', add_skill, name='add_skill'),
path('add_language', add_language, name='add_language'),
path('add_project', add_project, name='add_project'),

path('edit_language/<int:id>/', edit_language, name='edit_language'),

path('edit_skill/<int:id>/', edit_skill, name='edit_skill'),
path('edit_project/<int:id>/', edit_project, name='edit_project'),
path('edit_education/<int:id>/', edit_education, name='edit_education'),
path('edit_experience/<int:id>/', edit_experience, name='edit_experience'),
path('edit_project/<int:id>/', edit_project, name='edit_project'),

path('delete_language/<int:id>/', delete_language, name='delete_language'),
path('delete_skill/<int:id>/', delete_skill, name='delete_skill'),
path('delete_education/<int:id>/', delete_education, name='delete_education'),
path('delete_experience/<int:id>/', delete_experience, name='delete_experience'),
path('delete_project/<int:id>/', delete_project, name='delete_project'),

 path('myprofile/edit/skills',edit_skills,name='edit-skills'), 
 path('map',map_view,name='map'),
  path('other_user/<int:id>/',other_user,name='other_user'),
  path('', ProfileListView.as_view(), name='all-profiles-view'),
  path('my-invites/', invites_received_view, name='my-invites-view'),
  path('friends_list/', get_friends_list, name='friends_list_view'),
  path('send-invite/', send_invitation, name='send-invite'),
  path('remove-friend/', remove_from_friends, name='remove-friend'),
  path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
  path('my-invites/accept/', accept_invitation, name='accept-invite'),
  path('my-invites/reject/', reject_invitation, name='reject-invite'),
 ]

src/company_profile/models.py
from tkinter.tix import Tree
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from django.utils import timezone
from django.template.defaultfilters import slugify

CHOICES = (
    ('Full-Time', 'Full-Time'),
    ('Part-Time', 'Part-Time'),
    ('Internship', 'Internship'),
    ('Remote', 'Remote'),
)

class Company_profile(models.Model):

          user=models.OneToOneField(User,on_delete=models.CASCADE,default='')
          company_name=models.CharField(max_length=255)
          location = models.CharField(max_length=255)
          about_us=models.TextField(default='No bio....',max_length=2000)
          last_updated_time=models.DateTimeField(auto_now=True)
          employee_strength=models.IntegerField(blank=False,default=0)
          
          
          # slug=models.SlugField(unique=True, blank=True,max_length=1000)

          # def save(self, *args, **kwargs):
          #           set_slug=slugify(str(self.user)+"_"+str(self.first_name) + "_" + str(self.last_name))
          #           flag=False
          #           flag=Profile.objects.filter(slug=set_slug).exists()
          #           while flag == True:

          #           set_slug=slugify(set_slug+"_"+str(get_random_postfix()))
          #           flag=Profile.objects.filter(slug=set_slug).exists()
          #           self.slug=set_slug
          #           super().save( *args, **kwargs)

class Job(models.Model):

    company_userID =models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    company = models.CharField(max_length=200)
    location = models.CharField(max_length=255,default='-')
    description = models.TextField(blank=False,default='-')
    experience_required=models.CharField(max_length=200,blank=False,default='-')
    salary=models.IntegerField(blank=True,default=0)
    skills_req = models.CharField(max_length=200)
    job_type = models.CharField(
        max_length=30, choices=CHOICES, default='Full Time', null=True)
    link = models.URLField(null=True, blank=True)
#     slug = AutoSlugField(populate_from='title', unique=True, null=True)
    date_posted = models.DateTimeField(auto_now_add=True)
    deadline =models.DateTimeField(blank=False,null=True)

    def __str__(self):
        return self.title

class SavedJob(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    saved_time=models.DateTimeField(auto_now_add=True,null=True )
    def __str__(self):
        return self.job.title

# class Applicants(models.Model):
#     job = models.ForeignKey(
#         Job, related_name='applicants', on_delete=models.CASCADE)
#     applicant = models.ForeignKey(
#         User, related_name='applied', on_delete=models.CASCADE)
#     date_posted = models.DateTimeField(default=timezone.now)
#     date_applied=models.DateTimeField(default=timezone.now)

#     def __str__(self):
#         return self.applicant

class Application(models.Model):


    APPLICATION_CHOICES = (
        ('Active', 'ACTIVE'),
        ('Selected', 'SELECTED'),
        ('Rejected', 'REJECTED'),
        {'Interview', 'INTERVIEW'},
    )


    seeker = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField( auto_now=True)
    status = models.CharField(max_length=15,
                              choices=APPLICATION_CHOICES,
                              default='Active')
    comment=models.TextField(blank=True,max_length=250)

src/company_profile/forms.py
from django import forms
from .models import Job,Company_profile,Application
class Job_form(forms.ModelForm):
    class Meta:
        model=Job
        fields=('title','description','location','experience_required','salary','skills_req','job_type','deadline')
        widgets = {
            'deadline': forms.DateInput(attrs={'type': 'date'}),
        }

class Update_profile(forms.ModelForm):
    class Meta:
        model=Company_profile
        fields=('company_name','location','about_us','employee_strength')
        # widgets = {
        #      'about_us': forms.TextField(),
        #  }
        
class Application_Update(forms.ModelForm):
    class Meta:
        model=Application
        fields=('status','comment')

src/company_profile/views.py
from calendar import c
from email.mime import application
import re
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from .forms import Job_form,Update_profile,Application_Update
# Create your views here.
from .models import Job,Company_profile,Application,SavedJob

def check_if_starts(dic,word):
    
    return  {key:val for key, val in dic.items() 
                   if key.startswith(word)}

def view_applications(request,id):
     job=get_object_or_404(Job,id=id)
     if job.id!=id:
         return HttpResponseNotFound('<h1>Invalid access </h1>')
     applications=Application.objects.filter(job=job)
     if request.method=='POST':
         print(request.POST)
         re=request.POST
         form_id=int(re.get('id'))
         for app in applications:
             if app.seeker.id==form_id:
                 form=Application_Update(re,instance=app)
                 if form.is_valid():
                     form.save()

        
     forms=[Application_Update(instance=i) for i in applications]
     context={'applications':applications,
                        'forms':forms,
                        'zipped': zip(applications,forms)
                        }
     return render(request,'company_profile/view_applications.html',context)

def other_company(request,id):
    
    company=get_object_or_404(Company_profile,id=id)
    total_jobs = Job.objects.filter(company_userID=company.user).count()

    my_jobs=Job.objects.filter(company_userID=company.user)
    paginator = Paginator(my_jobs, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={
                    'my_jobs':my_jobs,
                    'page_obj':page_obj,
                    'company':company,
                    'total_jobs':total_jobs,}
    return render(request, 'company_profile/other_company.html',context)

def applied_job_list(request):
    applied_list = Application.objects.filter(seeker=request.user)
    paginator = Paginator(applied_list, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {

        'page_obj': page_obj,

    }
    return render(request, 'company_profile/applied_job_list.html', context)

def my_profile_company_view(request):


    company=get_object_or_404(Company_profile,user=request.user)
    total_jobs = Job.objects.filter(company_userID=request.user).count()
    
    job_form=Job_form()
    profile_form=Update_profile(instance=company)
    my_jobs=Job.objects.filter(company_userID=request.user)
    paginator = Paginator(my_jobs, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.method =='POST':
        
        re=request.POST
        print(re)
        if not not check_if_starts(re,'add_job'):
    
            current_job=Job.objects.create(company_userID=request.user  )
            current_job.title= re.get('title')
            current_job.description= re.get('description')
            current_job.experience_required= re.get('experience_required')
            current_job.skills_req= re.get('skills_req')
            current_job.job_type= re.get('job_type')
            current_job.deadline= re.get('deadline')
            current_job.company=company.company_name
            current_job.location=re.get('location')
            current_job.save()
            return redirect('/company_profile/myprofile')
        if not not check_if_starts(re,'profile_update'):
            profile_form=Update_profile(re,instance=company)
            if profile_form.is_valid():
                profile_form.save()
            return redirect('/company_profile/myprofile')
                

          
    context={
                    'profile_form':profile_form,
                    'my_jobs':my_jobs,
                    'page_obj':page_obj,
                    'job_form':job_form,
                    'company':company,
                    'total_jobs':total_jobs,}
    return render(request, 'company_profile/myprofile.html',context)

# @login_required(login_url=reverse_lazy('proconnect:login'))
def saved_job_list(request):

    saved_list = SavedJob.objects.filter(user=request.user)
    job_list=[s.job for s in saved_list]
    paginator = Paginator(job_list, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {

        'page_obj': page_obj,

    }
    return render(request, 'company_profile/saved_job_list.html', context)

def job_list(request):

    job_list = Job.objects.order_by('-date_posted')
    paginator = Paginator(job_list, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {

        'page_obj': page_obj,

    }
    return render(request, 'company_profile/job_list.html', context)



def single_job_view(request,id):
    print(request.user)
    print("id->",id)
    
    company=Company_profile.objects.filter(user=request.user)
    print(company.count())
    role='user'
    if company.count()==0:
        role='user'
    else :
        role='company'
    job_query = get_object_or_404(Job, id=id)
    saved=0
    if SavedJob.objects.filter(user=request.user,job=job_query).count()>0:
        saved=1
    applied=0
    if Application.objects.filter(seeker=request.user,job=job_query).count()>0:
        applied=1
   
    
            


    print(vars(job_query))
    context = {
        'job': job_query,
        'user': request.user,
        'role': role,
        'saved':saved,
        'applied':applied,
    }
    if request.method == 'POST':
        re= request.POST
        print(check_if_starts(re,'apply'))
        print(check_if_starts(re,'withdraw'))
        print(check_if_starts(re,'save'))
        print(check_if_starts(re,'unsave'))

        if not not check_if_starts(re,'apply'):
            print('apppling')
            Application.objects.create(seeker=request.user,job=job_query)
            return redirect('/company_profile/single_job/'+str(id))
        if  not not check_if_starts(re,'withdraw'):
            Application.objects.filter(seeker=request.user,job=job_query).delete()
            return redirect('/company_profile/single_job/'+str(id))
        if not not check_if_starts(re,'save'):
            print('saving')
            SavedJob.objects.create(user=request.user,job=job_query)
            return redirect('/company_profile/single_job/'+str(id))
        if not not check_if_starts(re,'unsave'):
            SavedJob.objects.filter(user=request.user,job=job_query).delete()
            return redirect('/company_profile/single_job/'+str(id))

            

    return render(request, 'company_profile/single_job.html', context)





def edit_job_view(request,id):
    if request.user!=Job.objects.get(id=id).company_userID:
        return HttpResponseNotFound('<h1>Invalid access </h1>')



    if request.method == 'POST':
        joob=Job.objects.get(id=id)
        if not not check_if_starts(request.POST,'add_job'):
            job_form=Job_form(request.POST,instance=joob)
            if job_form.is_valid():
                job_form.save()
            return redirect('/company_profile/myprofile')
        if not not check_if_starts(request.POST,'delete_job'):
            joob.delete()
            print('deleted')
            return redirect('/company_profile/myprofile')
    if Job.objects.filter(id=id).count()==0:
        return redirect('/company_profile/myprofile')
    else:
        job_form=Job_form(instance=Job.objects.get(id=id))
        context={'job_form':job_form}
        return render(request, 'company_profile/job_edit.html',context)

src/company_profile/templates/company_profile/applied_job_list.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}


  <div class="container">

    <div class="row">
      <h2>You have applied {{page_obj|length}} jobs.</h2>
      {% for app in page_obj %}
      <div class="col-xxl-6 col-md-12">
          <div class="card bg-light mb-3">
            <div class="card-header"> <h5>Application for job <a href= "{% url 'company_profile:single_job_view'   app.job.id  %}" > {{app.job.title }} @ {{app.job.company }}   </a> </h5>
            
            </div>

            <h5 class="card-title">Application status is : <span class="badge badge-primary">
              {{app.status}}
            </span> </h5>
            
            <h5 >Comment recieved: {{app.comment}}</h5 >
              <p class="card-text"><small class="text-muted">Last updated {{app.timestamp}}</small></p>
          </div>
        </div>


      {% endfor %}
    </div>
{% if page_obj.has_other_pages %}
<div class="row pagination-wrap">
  <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
    <span id="page_navigator">Showing {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} Pages</span>
  </div>
  <div class="col-md-6 text-center text-md-right">
    <div class="custom-pagination ml-auto">

      <span id="prev_page">
      {% if page_obj.has_previous %}
      <a id="ajax_paginator" href="?page={{ page_obj.previous_page_number }}" class="prev">Prev</a>
      {% endif %}
    </span>
      <span id="page_no">
        <div class="d-inline-block">
          {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
          <a id="ajax_paginator" class="ajax_paginator_{{ i }} active" href="?page={{ i }}">{{ i }}</a>

          {% else %}
          <a class="ajax_paginator_{{ i }}" id="ajax_paginator" href="?page={{ i }}">{{ i }}</a>
          {% endif %}
          {% endfor %}
        </div>
      </span>
      {% if page_obj.has_next %}
      <span id="next_page">
        <a id="ajax_paginator" class="next" href="?page={{ page_obj.next_page_number }}">Next</a>
      </span>
      {% endif %}

    </div>
  </div>
</div>
{% endif %}

  </div>
 



<style>
    main.form-group {
      /*center form inputs */
      float: none;
      margin: 0 auto;
    }

    main {
      /* center contents */
      text-align: center;
    }

    .card {
        margin: 10px;
        padding: 10px;
      height: 100%;
    }

    .form-control {
      align-self: flex-end;
    }
</style>
{% endblock content %}

src/company_profile/templates/company_profile/job_list.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}



<section id="ajax_listing_paginattion" class="site-section services-section bg-light block__62849" id="next-section">
  <div class="container">

    <div class="row">

      {% for job in page_obj %}
      <div class="col-xxl-6 col-md-12">
        <div class="card text-center">
          <h3>{{ job.title }}</h3>
          <ul class="job-listing-meta list-unstyled pl-3 mb-0">
            <li class="menu-fix mb-2">

              <span class="badge badge-primary">
                {{job.job_type}}
              </span>
          </li>
            <li class="badge badge-secondary menu-fix mb-2"> {{ job.location }}</li>
          </ul>
          <p>{{ job.description | safe | truncatechars:250}}</p>
          <a href="{% url 'company_profile:single_job_view' job.id %}" >
            <input type="submit"  name="withdraw" class="btn btn-block btn-primary btn-md" value="Read More" />
          </a>
          
          </div>
        </div>


          


     

      {% endfor %}
    </div>
{% if page_obj.has_other_pages %}
<div class="row pagination-wrap">
  <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
    <span id="page_navigator">Showing {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} Pages</span>
  </div>
  <div class="col-md-6 text-center text-md-right">
    <div class="custom-pagination ml-auto">

      <span id="prev_page">
      {% if page_obj.has_previous %}
      <a id="ajax_paginator" href="?page={{ page_obj.previous_page_number }}" class="prev">Prev</a>
      {% endif %}
    </span>
      <span id="page_no">
        <div class="d-inline-block">
          {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
          <a id="ajax_paginator" class="ajax_paginator_{{ i }} active" href="?page={{ i }}">{{ i }}</a>

          {% else %}
          <a class="ajax_paginator_{{ i }}" id="ajax_paginator" href="?page={{ i }}">{{ i }}</a>
          {% endif %}
          {% endfor %}
        </div>
      </span>
      {% if page_obj.has_next %}
      <span id="next_page">
        <a id="ajax_paginator" class="next" href="?page={{ page_obj.next_page_number }}">Next</a>
      </span>
      {% endif %}

    </div>
  </div>
</div>
{% endif %}

  </div>
</section>
 



<style>
    main.form-group {
      /*center form inputs */
      float: none;
      margin: 0 auto;
    }

    main {
      /* center contents */
      text-align: center;
    }

    .card {
        margin: 10px;
        padding: 10px;
      height: 100%;
    }

    .form-control {
      align-self: flex-end;
    }
</style>
{% endblock content %}

src/company_profile/templates/company_profile/myprofile.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
 <!-- end col-->



<div class="card-box">
<ul class="nav nav-pills navtab-bg">
    <li class="nav-item">
        
        <a href="#profile" data-toggle="tab" aria-expanded="true" class="nav-link ml-0 active" style="color:rgb(250, 250, 250);">
            <i class="mdi mdi-face-profile mr-1"></i>Profile
        </a>
    </li>
    <li class="nav-item">
        <a href="#add_job" data-toggle="tab" aria-expanded="false" class="nav-link" style="color:rgb(250, 250, 250);" >
          Add Job
        </a>
    </li>
    <li class="nav-item">
        <a href="#list_jobs" data-toggle="tab"  aria-expanded="false" class="nav-link" style="color:rgb(255, 255, 255);">
            <i class="mdi mdi-settings-outline mr-1"></i>Listed Jobs
        </a>
    </li>
    <li class="nav-item">
        <a href="#update_profile" data-toggle="tab"  aria-expanded="false" class="nav-link" style="color:rgb(255, 255, 255);">
            <i class="mdi mdi-settings-outline mr-1"></i>Update Profile
        </a>
    </li>
    
</ul>
<div class="tab-content">
<div class="tab-pane show active" id="profile">
        <div class="card border-dark mb-3">
          <div class="card-header"><h1>{{company.company_name}}</h1></div>
          <div class="card-body text-dark">
            <h5 class="card-title">About Us</h5>
            <p class="card-text">{{company.about_us}}</p>
          </div>
        </div>
        <div class="card-deck">
            <div class="card border-dark mb-3">
              <div class="card-body">
                <h5 class="card-title">Total jobs posted</h5>
                <p class="card-text">{{total_jobs}} job posted</p>
                <p class="card-text"><small class="text-muted">Last updated {{company.last_updated_time}}</small></p>
              </div>
            </div>
            <div class="card border-dark mb-3">
              <div class="card-body">
                <h5 class="card-title">Location</h5>
                <p class="card-text">We are located at {{company.location}}</p>
                <p class="card-text"><small class="text-muted">Last updated {{company.last_updated_time}}</small></p>
              </div>
            </div>
           <div class="card border-dark mb-3">
             <div class="card-body">
               <h5 class="card-title">Employee strength</h5>
               <p class="card-text">We have {{company.employee_strength}} employees. </p>
               <p class="card-text"><small class="text-muted">Last updated {{company.last_updated_time}}</small></p>
             </div>
           </div>
          </div>
</div>
<div class="tab-pane show " id="add_job">
  <form action='' method="post">

    {% csrf_token %}

       {{job_form|crispy}}
       <button type="submit" class="btn btn-block btn-primary btn-md" id="register_user_submit" name="add_job" data-mdb-ripple-color="dark">Submit</button>
   </form>
</div>


<div class="tab-pane show " id="list_jobs">
   


         <div class="container">

           <div class="row">
            {% if my_jobs|length == 0 %}
            <h2>No job listed </h2>
            {% endif %}
             {% for job in my_jobs %}
             <div class="col-xxl-6 col-md-12">
               <div class="card text-center">
                 <h3>{{ job.title }}</h3>
                 <ul class="job-listing-meta list-unstyled pl-3 mb-0">
                   <li class="menu-fix mb-2">

                     <span class="badge badge-primary">
                       {{job.job_type}}
                     </span>
                 </li>
                   <li class="badge badge-secondary menu-fix mb-2"> {{ job.location }}</li>
                 </ul>
                 <p>{{ job.description | safe | truncatechars:250}}</p>
                 <a href="{% url 'company_profile:edit_job_view' job.id %}" >
                   <input type="submit"   class="btn btn-block btn-primary btn-md" value="Edit Job" />
                 </a>
                 <a href="{% url 'company_profile:view_applications' job.id %}" >
                   <input type="submit"  class="btn btn-block btn-primary btn-md" value="Applications recieved" />
                 </a>

                 </div>
               </div>







             {% endfor %}
           </div>
     

         </div>
</div>

<div class="tab-pane show " id="update_profile">
   


      <div class="container">

        <form action='' method="post">

         {% csrf_token %}

            {{profile_form|crispy}}
            <button type="submit" class="btn btn-block btn-primary btn-md" id="register_user_submit" name="profile_update" data-mdb-ripple-color="dark">Submit</button>
        </form>
  

      </div>
</div>
</div>

</div>
<style>
    main.form-group {
      /*center form inputs */
      float: none;
      margin: 0 auto;
    }

    main {
      /* center contents */
      text-align: center;
    }

    .card {
        margin: 10px;
        padding: 10px;
      height: 100%;
    }

    .form-control {
      align-self: flex-end;
    }
</style>
{% endblock content %}

src/company_profile/templates/company_profile/saved_job_list.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}



<section id="ajax_listing_paginattion" class="site-section services-section bg-light block__62849" id="next-section">
  <div class="container">
<h2>You have saved {{page_obj|length}} jobs.</h2>

    <div class="row">

      {% for job in page_obj %}
      <div class="col-xxl-6 col-md-12">
        <div class="card text-center">
          <h3>{{ job.title }}</h3>
          <ul class="job-listing-meta list-unstyled pl-3 mb-0">
            <li class="menu-fix mb-2">

              <span class="badge badge-primary">
                {{job.job_type}}
              </span>
          </li>
            <li class="badge badge-secondary menu-fix mb-2"> {{ job.location }}</li>
          </ul>
          <p>{{ job.description | safe | truncatechars:250}}</p>
          <a href="{% url 'company_profile:single_job_view' job.id %}" >
            <input type="submit"  name="withdraw" class="btn btn-block btn-primary btn-md" value="Read More" />
          </a>
          
          </div>
        </div>


          


     

      {% endfor %}
    </div>
{% if page_obj.has_other_pages %}
<div class="row pagination-wrap">
  <div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
    <span id="page_navigator">Showing {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} Pages</span>
  </div>
  <div class="col-md-6 text-center text-md-right">
    <div class="custom-pagination ml-auto">

      <span id="prev_page">
      {% if page_obj.has_previous %}
      <a id="ajax_paginator" href="?page={{ page_obj.previous_page_number }}" class="prev">Prev</a>
      {% endif %}
    </span>
      <span id="page_no">
        <div class="d-inline-block">
          {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
          <a id="ajax_paginator" class="ajax_paginator_{{ i }} active" href="?page={{ i }}">{{ i }}</a>

          {% else %}
          <a class="ajax_paginator_{{ i }}" id="ajax_paginator" href="?page={{ i }}">{{ i }}</a>
          {% endif %}
          {% endfor %}
        </div>
      </span>
      {% if page_obj.has_next %}
      <span id="next_page">
        <a id="ajax_paginator" class="next" href="?page={{ page_obj.next_page_number }}">Next</a>
      </span>
      {% endif %}

    </div>
  </div>
</div>
{% endif %}

  </div>
</section>
 



<style>
    main.form-group {
      /*center form inputs */
      float: none;
      margin: 0 auto;
    }

    main {
      /* center contents */
      text-align: center;
    }

    .card {
        margin: 10px;
        padding: 10px;
      height: 100%;
    }

    .form-control {
      align-self: flex-end;
    }
</style>
{% endblock content %}