src/posts/urls.py
from django.urls import path
from .views import create_posts_and_comments, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', create_posts_and_comments, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

src/proconnect/urls.py
from turtle import home
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import include, path
from  django.conf import settings
from  django.conf.urls.static import static
from django.views.static import serve 
import  debug_toolbar
from .views import home_view,register_request_user,login_request,logout_view,register_request_company,search_results

# app_name = 'proconnect'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view,name='home_view' ),
    path('__debug__/', include('debug_toolbar.urls')),
    path('profiles/',include('profiles.urls',namespace='profiles')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('register_user/', register_request_user, name="register_user"),
    path('register_company/', register_request_company, name="register_company"),
    path('company_profile/',include('company_profile.urls',namespace='company_profile')),
    path('searchapp/',include('searchapp.urls',namespace='searchapp')),
     path("login", login_request, name="login"),
     path('search_results',search_results,name="search_results"),
     path("logout", logout_view, name="logout_view")
    ]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

src/profiles/urls.py
from django.urls import path
from .views import get_friends_list, my_profile_view,edit_skills,other_user,add_education,add_experience,add_skill,add_language,add_project,edit_language,edit_skill,edit_education,edit_project,edit_experience,delete_language,delete_skill,delete_education,delete_experience,delete_project,invites_received_view, profiles_list_view,invite_profiles_list_view, ProfileDetailView,ProfileListView,send_invitation,remove_from_friends,accept_invitation,reject_invitation,get_friends_list,map_view
app_name = 'profiles'

urlpatterns = [
 path('myprofile/', my_profile_view, name='my-profile-view'),
 path('add_education', add_education, name='add_education'),
 path('add_experience', add_experience, name='add_experience'),
 path('add_skill', add_skill, name='add_skill'),
path('add_language', add_language, name='add_language'),
path('add_project', add_project, name='add_project'),

path('edit_language/<int:id>/', edit_language, name='edit_language'),

path('edit_skill/<int:id>/', edit_skill, name='edit_skill'),
path('edit_project/<int:id>/', edit_project, name='edit_project'),
path('edit_education/<int:id>/', edit_education, name='edit_education'),
path('edit_experience/<int:id>/', edit_experience, name='edit_experience'),
path('edit_project/<int:id>/', edit_project, name='edit_project'),

path('delete_language/<int:id>/', delete_language, name='delete_language'),
path('delete_skill/<int:id>/', delete_skill, name='delete_skill'),
path('delete_education/<int:id>/', delete_education, name='delete_education'),
path('delete_experience/<int:id>/', delete_experience, name='delete_experience'),
path('delete_project/<int:id>/', delete_project, name='delete_project'),

 path('myprofile/edit/skills',edit_skills,name='edit-skills'), 
 path('map',map_view,name='map'),
  path('other_user/<int:id>/',other_user,name='other_user'),
  path('', ProfileListView.as_view(), name='all-profiles-view'),
  path('my-invites/', invites_received_view, name='my-invites-view'),
  path('friends_list/', get_friends_list, name='friends_list_view'),
  path('send-invite/', send_invitation, name='send-invite'),
  path('remove-friend/', remove_from_friends, name='remove-friend'),
  path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
  path('my-invites/accept/', accept_invitation, name='accept-invite'),
  path('my-invites/reject/', reject_invitation, name='reject-invite'),
 ]

src/searchapp/urls.py
from django.urls import path
from .views import search

app_name = 'searchapp'

urlpatterns = [
path('search', search, name='search'),


 ]

src/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
<a href="login" class="btn btn-rounded">Sign In</a>
<a href="register" class="btn btn-rounded">Sign Up</a>
{% endblock content %}

{% block scripts %}
<script>

</script>
{% endblock scripts %}

src/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:friends_list_view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
<div class="ui inverted menu nav mb-7">
    <div class="ui container">
      <a href="/" class="item">
          <h3>proConnect</h3>
      </a>
     {% if request.user.is_authenticated %}
     {% if request.user.profile %}

       <a href="/profiles/myprofile" class="item">
           My Profile
       </a>
       {% endif %}
       {% endif %}
       {% if request.user.is_authenticated %}
       {% if request.user.profile %}
         <a href="/posts" class = "item">Posts</a>
       {% endif %}
       {% endif %}
       {% if request.user.is_authenticated %}
       {% if request.user.company_profile %}
         <a href="/company_profile/myprofile" class="item">
             My Profile
         </a>
         {% endif %}
         {% endif %}
  

 
      {% if request.user.is_authenticated %}
      {% if request.user.profile %}
      <div class="dropdown">
        <button onclick="myFunction1()" class="dropbtn">Jobs</button>
        <div id="myDropdown1" class="dropdown-content">
        <a href="/company_profile/job_list">All Jobs</a>
          <a href="/company_profile/saved_job_list">Saved Jobs</a>
          <a href="/company_profile/applied_job_list">Applied Jobs</a>
        </div>
      </div> 
      {% endif %}
      {% endif %}
    
  
      <div class="right menu">
        {% if request.user.is_authenticated %}
        {% if request.user.profile %}
        {% if request.user.profile.account_type == 'U' %}
        <div class="dropdown">
            <button onclick="myFunction2()" class="dropbtn">Friends</button>

              <div id = "myDropdown2" class="dropdown-content">
                      <a href="/profiles">All Profiles</a>
                    <a href="{{path_to_invites}}">
                        My Friends
                    </a>
                    <a href="{{path_to_my_invites}}">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
        {% endif %}
        {% endif %}
        {% endif %}
          {% if request.user.is_authenticated %}
         
               <div class="item">
                  <div class="ui action left icon input">
                  
                      <a href="{% url 'searchapp:search' %}" class="ui item">
                        <button type='submit' class="ui button">Search</button>
                      </a>
                    
                    
                  
                  </div>
              </div>
              

              <a href="" class="item">
                   {{ request.user }}
              </a>
  
              <a href="{% url 'logout_view' %}" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>